# Generated by Django 4.0.2 on 2022-03-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_topic_options_topic_created_topic_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated',
        ),
    ]
