# Generated by Django 4.0.2 on 2022-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
